[build]
  functions = "functions"
  publish = "public"

[functions]
  api = { timeout = 30 }

[[redirects]]
  from = "/transcript/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200 